services:
  laravel9-php81:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PHP_VERSION: "8.1"
        LARAVEL_VERSION: "9"
        TESTBENCH_VERSION: "7.*"
        PHPUNIT_VERSION: "9.*"

  laravel10-php82:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PHP_VERSION: "8.2"
        LARAVEL_VERSION: "10"
        TESTBENCH_VERSION: "8.*"
        PHPUNIT_VERSION: "10.*"

  laravel11-php83:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PHP_VERSION: "8.3"
        LARAVEL_VERSION: "11"
        TESTBENCH_VERSION: "9.*"
        PHPUNIT_VERSION: "11.*"

  laravel12-php84:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PHP_VERSION: "8.4"
        LARAVEL_VERSION: "12"
        TESTBENCH_VERSION: "10.*"
        PHPUNIT_VERSION: "11.*"

  laravel13-php84:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PHP_VERSION: "8.4"
        LARAVEL_VERSION: "13"
        TESTBENCH_VERSION: "11.*"
        PHPUNIT_VERSION: "12.*"
